/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    inquiries: Inquiry;
    'blog-posts': BlogPost;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh-HK' | 'zh-CN' | 'en')
    | ('zh-HK' | 'zh-CN' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'zh-HK' | 'zh-CN' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * 用於網頁 URL，例如：hk-company-incorporation
   */
  slug: string;
  /**
   * 頁面頂部橫幅圖片 (選填，不填將使用預設背景)
   */
  bannerImage?: (number | null) | Media;
  shortDescription: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * 參考價格 (港幣 HKD)，留空表示「請諮詢我們」
   */
  price?: number | null;
  icon?: ('briefcase' | 'shield' | 'file-text' | 'award' | 'map-pin') | null;
  /**
   * 自訂聯絡按鈕文字，如「免費獲取報價」或「立即諮詢」 (選填，留空將使用預設文字)
   */
  ctaText?: string | null;
  /**
   * 自訂價格後綴，例如：「+」或「起」或「起/年」 (選填，留空將顯示「+」)
   */
  priceSuffix?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  phone: string;
  service?: (number | null) | Service;
  message?: string | null;
  status?: ('pending' | 'contacted' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * 用於網址路徑，例如：hong-kong-tax-filing-guide
   */
  slug: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * 網址路徑，例如：about-us
   */
  slug: string;
  /**
   * 頁面頂部橫幅圖片 (選填，不填將使用預設背景)
   */
  bannerImage?: (number | null) | Media;
  shortDescription?: string | null;
  /**
   * 頁面徽章/小標題 (選填，如：專業顧問對接)
   */
  badge?: string | null;
  /**
   * 頁面特色列表 (選填，例如諮詢頁面的左側特色清單)
   */
  features?:
    | {
        title: string;
        description: string;
        icon?: ('check' | 'users' | 'dollar') | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * 詢價頁面表單的自訂欄位名稱與提示訊息 (僅在 slug 為 inquiry 時顯示)
   */
  inquiryFormSettings?: {
    formTitle?: string | null;
    formDescription?: string | null;
    labelName?: string | null;
    placeholderName?: string | null;
    labelEmail?: string | null;
    placeholderEmail?: string | null;
    labelPhone?: string | null;
    placeholderPhone?: string | null;
    labelService?: string | null;
    selectEmptyText?: string | null;
    labelMessage?: string | null;
    placeholderMessage?: string | null;
    submitBtnText?: string | null;
    submittingText?: string | null;
    successTitle?: string | null;
    successDescription?: string | null;
    successBackBtnText?: string | null;
    /**
     * 不同服務的動態提示文字。
     */
    serviceHints?:
      | {
          /**
           * 服務的 slug，必須與服務的網址路徑一致，例如：hk-company
           */
          serviceSlug: string;
          hintText: string;
          id?: string | null;
        }[]
      | null;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  bannerImage?: T;
  shortDescription?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  price?: T;
  icon?: T;
  ctaText?: T;
  priceSuffix?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  content?: T;
  publishedDate?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  bannerImage?: T;
  shortDescription?: T;
  badge?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  inquiryFormSettings?:
    | T
    | {
        formTitle?: T;
        formDescription?: T;
        labelName?: T;
        placeholderName?: T;
        labelEmail?: T;
        placeholderEmail?: T;
        labelPhone?: T;
        placeholderPhone?: T;
        labelService?: T;
        selectEmptyText?: T;
        labelMessage?: T;
        placeholderMessage?: T;
        submitBtnText?: T;
        submittingText?: T;
        successTitle?: T;
        successDescription?: T;
        successBackBtnText?: T;
        serviceHints?:
          | T
          | {
              serviceSlug?: T;
              hintText?: T;
              id?: T;
            };
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  /**
   * 網站標誌 (Logo)
   */
  logoImage?: (number | null) | Media;
  logoText?: string | null;
  email: string;
  phone: string;
  /**
   * WhatsApp 聯絡連結
   */
  whatsapp: string;
  /**
   * 網頁頂部顯示的 WhatsApp 號碼文字
   */
  whatsappDisplay: string;
  hkAddress: string;
  szAddress: string;
  /**
   * 深圳辦公室電話
   */
  szPhone: string;
  /**
   * 深圳辦公室 WhatsApp 連結
   */
  szWhatsapp: string;
  beijingAddress: string;
  singaporeAddress: string;
  licenseText: string;
  licenseLink: string;
  /**
   * 主導航選單項目（最多支援 3 層嵌套，各語言分別填寫）
   */
  navigationMenu?:
    | {
        label: string;
        link: string;
        subMenuItems?:
          | {
              label: string;
              link: string;
              nestedMenuItems?:
                | {
                    label: string;
                    link: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  priceLabel?: string | null;
  serviceCtaFallback?: string | null;
  backToHomeLabel?: string | null;
  inquireMoreLabel?: string | null;
  addToCartLabel?: string | null;
  learnMoreLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  slides?:
    | {
        title: string;
        subtitle?: string | null;
        description?: string | null;
        button1Text?: string | null;
        button1Link?: string | null;
        button2Text?: string | null;
        button2Link?: string | null;
        /**
         * 背景圖片 (不選擇則使用預設圖片)
         */
        backgroundImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  servicesHighlight?:
    | {
        title: string;
        /**
         * 背景圖片 (不選擇則使用預設圖片)
         */
        bgImage?: (number | null) | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  featuredTitle?: string | null;
  featuredSubtitle?: string | null;
  tabHkTitle?: string | null;
  tabOffshoreTitle?: string | null;
  tabTrademarkTitle?: string | null;
  hkPlans?:
    | {
        title: string;
        price: string;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * 預填詢價方案名稱，例如：基本香港有限公司成立
         */
        inquiryPlanName?: string | null;
        moreLink?: string | null;
        id?: string | null;
      }[]
    | null;
  offshorePlans?:
    | {
        title: string;
        price: string;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        inquiryPlanName?: string | null;
        moreLink?: string | null;
        id?: string | null;
      }[]
    | null;
  trademarkPlans?:
    | {
        title: string;
        price: string;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        inquiryPlanName?: string | null;
        moreLink?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutTitle?: string | null;
  aboutContent?: string | null;
  whyTitle?: string | null;
  whyContent?: string | null;
  /**
   * 「成立公司簡單」圖片 (對應預設的 company-formation-01.jpg)
   */
  whyImage1?: (number | null) | Media;
  /**
   * 「成立策略」圖片 (對應預設的 company-formation-02.png)
   */
  whyImage2?: (number | null) | Media;
  advantagesTitle?: string | null;
  advantages?:
    | {
        title: string;
        paragraph1?: string | null;
        paragraph2?: string | null;
        id?: string | null;
      }[]
    | null;
  faqTitle?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  contactTitle?: string | null;
  contactDesc?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  logoImage?: T;
  logoText?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  whatsappDisplay?: T;
  hkAddress?: T;
  szAddress?: T;
  szPhone?: T;
  szWhatsapp?: T;
  beijingAddress?: T;
  singaporeAddress?: T;
  licenseText?: T;
  licenseLink?: T;
  navigationMenu?:
    | T
    | {
        label?: T;
        link?: T;
        subMenuItems?:
          | T
          | {
              label?: T;
              link?: T;
              nestedMenuItems?:
                | T
                | {
                    label?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  priceLabel?: T;
  serviceCtaFallback?: T;
  backToHomeLabel?: T;
  inquireMoreLabel?: T;
  addToCartLabel?: T;
  learnMoreLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        button1Text?: T;
        button1Link?: T;
        button2Text?: T;
        button2Link?: T;
        backgroundImage?: T;
        id?: T;
      };
  servicesHighlight?:
    | T
    | {
        title?: T;
        bgImage?: T;
        link?: T;
        id?: T;
      };
  featuredTitle?: T;
  featuredSubtitle?: T;
  tabHkTitle?: T;
  tabOffshoreTitle?: T;
  tabTrademarkTitle?: T;
  hkPlans?:
    | T
    | {
        title?: T;
        price?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        inquiryPlanName?: T;
        moreLink?: T;
        id?: T;
      };
  offshorePlans?:
    | T
    | {
        title?: T;
        price?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        inquiryPlanName?: T;
        moreLink?: T;
        id?: T;
      };
  trademarkPlans?:
    | T
    | {
        title?: T;
        price?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        inquiryPlanName?: T;
        moreLink?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutContent?: T;
  whyTitle?: T;
  whyContent?: T;
  whyImage1?: T;
  whyImage2?: T;
  advantagesTitle?: T;
  advantages?:
    | T
    | {
        title?: T;
        paragraph1?: T;
        paragraph2?: T;
        id?: T;
      };
  faqTitle?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  contactTitle?: T;
  contactDesc?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}